#!/bin/sh

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

urls="$(sed 's/.*│//g' | tr -d '\n' | grep -aEo "${urlregex}" | uniq |
		sed "s/\(\.\|,\|;\|\!\\|\?\)$//;s/^www./http:\/\/www\./")"

[ -z "${urls}" ] && exit 1

while getopts "oc" o; do case "${o}" in
	o) chosen="$(echo "${urls}" | dmenu -i -p 'Follow which url?')"
			setsid xdg-open "${chosen}" >/dev/null 2>&1 & ;;
	c) echo "${urls}" | dmenu -i -p 'Copy which url?' | tr -d '\n' | xclip -selection clipboard ;;
	*) exit 1 ;;
esac done
