#!/bin/sh

cachedir=${XDG_CACHE_HOME:-"${HOME}/.cache/dmenu/"}
cache="${cachedir}/dmenu_run"

[ ! -e "${cachedir}" ] && mkdir -p "${cachedir}"

IFS=:
if stest -dqr -n "${cache}" "${PATH}"; then
	stest -flx "${PATH}" | sort -u > "${cache}"
fi

< "${cache}" dmenu "$@" | ${SHELL:-"/bin/sh"} &
