#!/bin/sh

cachedir=${XDG_CACHE_HOME:-"${HOME}/.cache"}
cache=${cachedir}/dmenu_run
historyfile=${cachedir}/dmenu_history

IFS=:
if stest -dqr -n "${cache}" "${PATH}"; then
	stest -flx "${PATH}" | sort -u | tee "${cache}"
else
	cat "${cache}"
fi
unset IFS

awk -v histfile="${historyfile}" '
	BEGIN {
		while( (getline < histfile) > 0 ) {
			sub("^[0-9]+\t","")
			print
			x[$0]=1
		}
	} !x[$0]++ ' "${cache}" \
	| dmenu "$@" \
	| awk -v histfile="${historyfile}" '
		BEGIN {
			FS=OFS="\t"
			while ( (getline < histfile) > 0 ) {
				count=$1
				sub("^[0-9]+\t","")
				fname=$0
				history[fname]=count
			}
			close(histfile)
		}

		{
			history[$0]++
			print
		}

		END {
			if(!NR) exit
			for (f in history)
				print history[f],f | "sort -k1rn >" histfile
		} '	| while read -r cmd; do ${SHELL:-"/bin/sh"} -c "${cmd}" & done



#
# Override dmenu_path sorting results by atime. TESTING
#

#echo "${PATH}" | tr ':' '\n' | uniq | sed 's#$#/#' | xargs ls -lt --time-style=+%s | 
#		awk '/^(-|l)/ { print $6, $7 }' | sort -rn | cut -d' ' -f2
