#!/bin/sh

coords=$(xwininfo -id "$(xdotool getactivewindow || :)" | sed -n \
		-e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x:\ \1/p" \
        -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y:\ \1/p" \
        -e "s/^ \+Width: \+\([0-9]\+\).*/w:\ \1/p" \
		-e "s/^ \+Height: \+\([0-9]\+\).*/h:\ \1/p")

props=$(xprop | awk '
	/^WM_CLASS/{sub(/.* =/, "instance:"); sub(/,/, "\nclass:"); print}
	/^WM_NAME/{sub(/.* =/, "title:"); print}')

notify-send  "${props}" "${coords}"
